globals:
  simulator-arguments:
    sampling-frequency: 4096
    duration: 4096
    total-duration: "2 hours"
    start-time: 1577491218
  working-directory: "./ET_2L_Aligned_BBH"
  output-directory: output
  metadata-directory: metadata

simulators:
  signal:
    class: CBCSignalSimulator
    arguments:
      population_file: https://sandbox.zenodo.org/records/413548/files/18321_1yrCatalogBBH.h5
      waveform_model: IMRPhenomXPHM
      waveform_arguments:
          reference_frequency: 50
      minimum_frequency: 20
      detectors:
        - E1_2L_aligned_sardinia
        - E2_2L_aligned_emr
    output:
      file_name: "E-{{ detectors }}_STRAIN_BBH-{{ start_time }}-{{ duration }}.gwf"
      arguments:
        channel: "{{ detectors }}:STRAIN"
