globals:
  working-directory: .
  simulator-arguments:
    sampling-frequency: 4096
    max-samples: 22
    duration: 4096
    start_time: 1577491218
  output-arguments: {}
  output-directory: ET_Triangle_EMR_BBH
  metadata-directory: ET_Triangle_EMR_BBH/metadata
simulators:
  noise:
    class: CBCSimulator
    arguments:
      population_file: 18321_1yrCatalogBBH.h5
      waveform_model: IMRPhenomXPHM,
      waveform_arguments: {'earth_rotation': True, 'time_dependent_timedelay': True}
      minimum_frequency: 2,
      detectors:
        - E1_Triangle_EMR
        - E2_Triangle_EMR
        - E3_Triangle_EMR
    output:
      file_name: "E-{{ detector }}_STRAIN_BBH-{{ start_time }}-{{ duration }}.gwf"
      arguments:
        channel: STRAIN
