globals:
  simulator-arguments:
    sampling-frequency: 4096
    duration: 4096
    total-duration: "1 day"
    start-time: 1577491218
  working-directory: "./ET_Triangle_Sardinia_BNS"
  output-directory: output
  metadata-directory: metadata

simulators:
  signal:
    class: CBCSignalSimulator
    arguments:
      population_file: https://sandbox.zenodo.org/records/413548/files/18321_1yrCatalogBNS.h5
      waveform_model: IMRPhenomPv2_NRTidalv2
      waveform_arguments:
          reference_frequency: 50
      minimum_frequency: 20
      detectors:
        - E1_triangle_sardinia
        - E2_triangle_sardinia
        - E3_triangle_sardinia
    output:
      file_name: "E-{{ detectors }}_STRAIN_BNS-{{ start_time }}-{{ duration }}.gwf"
      arguments:
        channel: "{{ detectors }}:STRAIN"
