globals:
  working-directory: .
  simulator-arguments:
    sampling-frequency: 4096
    max-samples: 22
    duration: 4096
    start_time: 1577491218
  output-arguments: {}
  output-directory: ET_Triangle_EMR_noise
  metadata-directory: ET_Triangle_EMR_noise/metadata
simulators:
  noise:
    class: ColoredNoise
    arguments:
      psd_file: ET_10_full_cryo_psd.txt
      detectors:
        - E1_Triangle_EMR
        - E2_Triangle_EMR
        - E3_Triangle_EMR
      seed: 0
    output:
      file_name: "E-{{ detector }}_STRAIN_NOISE-{{ start_time }}-{{ duration }}.gwf"
      arguments:
        channel: STRAIN
